version: "3.9"

services:
  entry-point:
    build: entry-point
    ports:
      - "8080:8080"
  load-balancer-master:
    build:
      context: load-balancer
      args:
        role: master
    cap_add:
      - NET_ADMIN
  load-balancer-backup:
    build:
      context: load-balancer
      args:
        role: backup
    cap_add:
      - NET_ADMIN
  web-app:
    build: .
    deploy:
      replicas: 2

networks:
  default:
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
